In [1]:
import numpy as np

In [2]:
arr1=[[1 , 2],
     [3 , 4]]
type(arr1)

list

In [3]:
arr2=[[11 ,12 ],
     [13 , 14]]
type(arr2)

list

In [11]:
arr1 = np.array(arr1)
arr2 = np.array(arr2)
arr3 = np.concatenate((arr1 , arr2) , axis = 0)
arr3

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [12]:
arr3.shape

(4, 2)

In [13]:
arr3=arr1+arr2
arr3

array([[12, 14],
       [16, 18]])

In [14]:
arr3=arr1 * arr2
arr3

array([[11, 24],
       [39, 56]])

In [15]:
arr3.reshape( 1 ,4)

array([[11, 24, 39, 56]])

In [16]:
arr1=list(range(100000))
arr2=list(range(100000 , 200000))

np_arr1=np.array(arr1)
np_arr2=np.array(arr2)

In [18]:
%%time
result=0
for x1, y1 in zip(arr1, arr2):
    result=result+(x1*y1)
result

CPU times: total: 15.6 ms
Wall time: 44.5 ms


833323333350000

In [19]:
%%time
np.dot(np_arr1 , np_arr2)

CPU times: total: 0 ns
Wall time: 0 ns


893678192

In [20]:
np.matmul(np_arr1 , np_arr2)

893678192

In [ ]:
#working with csv file

Working with CSV data files
Numpy also provides helper functions reading from & writing to files. Let's download a file climate.txt, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:

temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
This format of storing data is known as comma-separated values or CSV.

In [21]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2115812b650>)

In [22]:
climate_data=np.genfromtxt('climate.txt',delimiter=',' , skip_header=1)

In [23]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [24]:
climate_data.shape

(10000, 3)

In [30]:
reshap=climate_data.reshape(1000 ,5, 6 )

In [31]:
reshap

array([[[25., 76., 99., 39., 65., 70.],
        [59., 45., 77., 84., 63., 38.],
        [66., 50., 52., 41., 94., 77.],
        [91., 57., 96., 49., 96., 99.],
        [67., 20., 28., 85., 31., 95.]],

       [[78., 46., 34., 31., 40., 63.],
        [52., 77., 85., 28., 66., 77.],
        [32., 50., 57., 31., 79., 53.],
        [45., 76., 48., 80., 52., 27.],
        [24., 45., 90., 20., 89., 84.]],

       [[32., 20., 96., 56., 44., 74.],
        [93., 70., 80., 62., 87., 73.],
        [85., 48., 90., 87., 86., 93.],
        [43., 57., 69., 28., 71., 44.],
        [44., 95., 58., 88., 48., 46.]],

       ...,

       [[52., 39., 20., 85., 84., 29.],
        [83., 91., 59., 42., 23., 34.],
        [50., 51., 66., 24., 81., 56.],
        [49., 66., 41., 64., 91., 65.],
        [45., 77., 34., 76., 79., 93.]],

       [[77., 42., 58., 72., 69., 35.],
        [92., 63., 60., 32., 88., 30.],
        [67., 57., 42., 73., 60., 78.],
        [64., 94., 57., 82., 44., 35.],
        [31., 64., 

In [32]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [33]:
weights = np.array([0.3, 0.2, 0.5])

In [34]:
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [35]:
yields.shape

(10000,)

In [39]:
# yields.reshape(10000 , 1)
#converted in the form of column

In [42]:
climate_result=np.concatenate((climate_data ,yields.reshape(10000 , 1)) , axis=1)
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [44]:
np.savetxt('climate_results.txt', 
           climate_result, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

# Arithmetic operation , brodcasting and Comparision

In [45]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [46]:
arr2.shape

(3, 4)

In [47]:
arr3 = np.array([7, 8])
arr3.shape

(2,)

In [50]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [51]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])