In [10]:
import numpy as np
lst=[1 , 2 , 3 , 4 ,5 , 6, 7,8]
print(lst)

[1, 2, 3, 4]


In [13]:
ar1=np.array(lst)
print(ar1)

[1 2 3 4]


In [15]:
type(ar1)

numpy.ndarray

In [16]:
lst1=[10 , 11 , 12 ,13 , 14 ,15 ,16]
ar1=np.array(lst1)
print(ar1)

[10 11 12 13]


In [18]:
lst2=[20 , 21 ,22 ,23 ,24 ,25]
ar1=np.array([lst ,lst1 ,lst2])
print(ar1)

[[ 1  2  3  4]
 [10 11 12 13]
 [20 21 22 23]]


In [21]:
print(ar1.shape)

(3, 4)


In [29]:
lst3=[30 , 31 ,32 ,33,34]
lst4=[40 ,41 ,42 ,43, 44]
lst5=[50 ,51, 52 , 53 ,54]
ar1=np.array([lst , lst1 , lst2  ])
print(ar1)

[[ 1  2  3  4]
 [10 11 12 13]
 [20 21 22 23]]


In [30]:
ar1.shape

(3, 4)

In [31]:
ar1.reshape(2,6)

array([[ 1,  2,  3,  4, 10, 11],
       [12, 13, 20, 21, 22, 23]])

In [41]:
ar2=np.zeros(3)
print(ar2)

[0. 0. 0.]


In [44]:
ar3=np.ones(6)+3
print(ar3)

[4. 4. 4. 4. 4. 4.]


In [52]:
mat1=np.array([lst])
print(mat1)
num=input("Enter Number")
print(num)


[[1 2 3 4]]
Enter Number12
12


In [58]:
# size=int(input("Size of Array"))
# arr=[]
# for i in range(size):
#     n=int(input(f"Enter {i} Element "))
#     arr.append(n)
# arr=np.array(arr)
# print(arr)

In [63]:
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [73]:
arr1=np.arange(100 ,150)
print(arr1)
arr1.reshape(2 ,25)
print(arr1)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


ValueError: cannot reshape array of size 51 into shape (2,25)